catalogSource:
  name: operator-catalog-4-10
  namespace: openshift-marketplace
  displayName: "RH Operator Catalog 4.10 (Disconnected)"
  image: "registry.redhat.io/redhat/redhat-operator-index:v4.10"

subscriptions:
  jaeger:
    namespace: openshift-operators
    channel: stable
    installPlanApproval: Manual
    name: jaeger-product
    startingCSV: jaeger-operator.v1.42.0-5
  kiali-ossm:
    namespace: openshift-operators
    channel: stable
    installPlanApproval: Manual
    name: kiali-ossm
    startingCSV: kiali-operator.v1.65.6
  servicemesh:
    namespace: openshift-operators
    channel: stable
    installPlanApproval: Manual
    name: servicemeshoperator
    startingCSV: servicemeshoperator.v2.4.0
